import { Briefcase, Dumbbell, GraduationCap, Grid, Scissors, Stethoscope } from "lucide-react"

// Sample professionals data
export const professionals = [
  {
    id: 1,
    name: "Dr. María González",
    specialty: "Medicina General",
    category: "salud",
    location: "Palermo, CABA",
    rating: 4.9,
    reviews: 127,
    image: "/doctora.png",
    price: "$3,500",
    availability: "Disponible hoy",
    description: "Médica especialista en medicina general con 15 años de experiencia.",
    services: ["Consulta General", "Chequeos", "Certificados"],
    schedule: "Lun-Vie 9:00-18:00",
    phone: "+54 11 1234-5678",
    email: "maria.gonzalez@email.com",
  },
  {
    id: 2,
    name: "Lic. Carlos Rodríguez",
    specialty: "Psicología",
    category: "salud",
    location: "Recoleta, CABA",
    rating: 4.8,
    reviews: 89,
    image: "/psicologo.png",
    price: "$4,000",
    availability: "Próximo turno: Mañana",
    description: "Psicólogo clínico especializado en terapia cognitivo-conductual.",
    services: ["Terapia Individual", "Terapia de Pareja", "Evaluaciones"],
    schedule: "Lun-Sáb 10:00-20:00",
    phone: "+54 11 2345-6789",
    email: "carlos.rodriguez@email.com",
  },
  {
    id: 3,
    name: "Estilista Ana Martín",
    specialty: "Peluquería y Estética",
    category: "belleza",
    location: "Villa Crespo, CABA",
    rating: 4.7,
    reviews: 203,
    image: "/estilista.png",
    price: "$2,800",
    availability: "Disponible hoy",
    description: "Estilista profesional con especialización en colorimetría.",
    services: ["Corte", "Color", "Peinados", "Tratamientos"],
    schedule: "Mar-Sáb 9:00-19:00",
    phone: "+54 11 3456-7890",
    email: "ana.martin@email.com",
  },
  {
    id: 4,
    name: "Abg. Roberto Silva",
    specialty: "Derecho Laboral",
    category: "legal",
    location: "Microcentro, CABA",
    rating: 4.9,
    reviews: 156,
    image: "/abogado.png",
    price: "$5,000",
    availability: "Próximo turno: Lunes",
    description: "Abogado especialista en derecho laboral y previsional.",
    services: ["Consulta Legal", "Despidos", "Jubilaciones"],
    schedule: "Lun-Vie 9:00-17:00",
    phone: "+54 11 4567-8901",
    email: "roberto.silva@email.com",
  },
  {
    id: 5,
    name: "Prof. Laura Fernández",
    specialty: "Entrenamiento Personal",
    category: "fitness",
    location: "Belgrano, CABA",
    rating: 4.8,
    reviews: 94,
    image: "/entrenadora.png",
    price: "$3,200",
    availability: "Disponible hoy",
    description: "Entrenadora personal certificada en fitness y nutrición.",
    services: ["Entrenamiento Personal", "Planes Nutricionales", "Evaluación Física"],
    schedule: "Lun-Sáb 6:00-22:00",
    phone: "+54 11 5678-9012",
    email: "laura.fernandez@email.com",
  },
  {
    id: 6,
    name: "Dra. Patricia López",
    specialty: "Odontología",
    category: "salud",
    location: "San Telmo, CABA",
    rating: 4.9,
    reviews: 178,
    image: "/dentista.png",
    price: "$4,500",
    availability: "Próximo turno: Miércoles",
    description: "Odontóloga especialista en estética dental y implantes.",
    services: ["Limpieza", "Blanqueamiento", "Implantes", "Ortodoncia"],
    schedule: "Lun-Vie 8:00-18:00",
    phone: "+54 11 6789-0123",
    email: "patricia.lopez@email.com",
  },
]

export const categories = [
  { id: "todos", name: "Todos", icon: Grid, count: professionals.length },
  { id: "salud", name: "Salud", icon: Stethoscope, count: 3 },
  { id: "belleza", name: "Belleza", icon: Scissors, count: 1 },
  { id: "legal", name: "Legal", icon: Briefcase, count: 1 },
  { id: "fitness", name: "Fitness", icon: Dumbbell, count: 1 },
  { id: "educacion", name: "Educación", icon: GraduationCap, count: 0 },
]

export const timeSlots = [
        "09:00",
        "09:30",
        "10:00",
        "10:30",
        "11:00",
        "11:30",
        "12:00",
        "12:30",
        "14:00",
        "14:30",
        "15:00",
        "15:30",
        "16:00",
        "16:30",
        "17:00",
        "17:30",
        "18:00",
        "18:30",
]